<!DOCTYPE html>
	<html lang="<?= $this->_lang?>" >
	<head>
		<? include($pathCommons."includes/head.phtml");?>
	</head>
	<body>
		<article>
		    <header>
			   	<? include($pathCommons."includes/botonera.phtml");?>	
			</header>
			
			<? include($pathCommons."includes/menu.phtml");?>
			
			<section class="doscolumnas">
	            <? if(!empty($menu)){?>
					<h1><?= $this->_title ?><span class="small"><?=$this->_description?></span></h1>
				<? } ?>
				<div id="msg" class="oculto" ></div>
				<fieldset>
	        		<?	include_once($pathVista.'controllers'. DS . $this->_controller .".phtml"); ?>
	        	</fieldset>
		  	</section>
		    
		    <aside id="rightmenu">
		    	<? include($pathCommons."includes/columna_derecha.phtml");?>
		    </aside>
		    
		    
		    <footer><p><?= _("powered") . " " . APP . " " . APP_VERSION?></p></footer>
	    </article>
	</body>
</html>