<? if (isset($_SESSION['usuario'])){ ?>
<div class="botonera">
	<ul>
	<li class="separata"><a href="<?= $this->_baseUrl ?>" id="id_inicio"><img src="<?=URL_IMG_ADMIN?>home.png" title="<?= _("home") ?>" /></a></li>
	<? $numPerfiles = count($usuario->getPerfiles());
		if($numPerfiles>1){
			$i = 1;
			foreach($usuario->getPerfiles() as $perfil){
			$profile = $perfil->profile;
	?>	
			<li class="<?=$i==$numPerfiles ? "separata" : "" ?>">
				<a href='#' id='<?= $perfil->id ?>' class="profile" title="<?=$profile ." - ".  _("profile.".$perfil->profile.".description") ?>">
					<img width="90px" height="90px" src='<?= $urlCommons."img/profiles/".$perfil->logo?>' />
				</a>
			</li>
	<? 		
			$i++;
			}
		} 
	?>
	<li class="separata"><a href="<?= $this->_baseUrl ?>anyo" id='id_cambio_edicion' title="<?= $edicion->nombre?> - <?= $this->_anyo?>"><img src="<?=URL_SKINS.$this->_anyo . "/" . IMG . "/". $edicion->cartel?>" /></a></li>
	<li class="separata"><a href="<?= $this->_baseUrl ?>viewusuario/<?=$usuario->getId()?>" ><img src="<?=BASE_URL_ADMIN . '/vista/skins/commons/img/usuarios/'. $usuario->getLogo()?>" title="<?= $usuario->getNombre()?>" /></a></li>
	<li class="separata"><a href="<?= $this->_baseUrl ?>logout" ><img src="<?=URL_IMG_ADMIN?>exit.png" title="<?= _("logout") ?>" /></a></li>
	</ul>
</div>
<? }?>