<? if (isset($_SESSION['usuario'])){ ?>
<div class="botonera">
	<ul>
	<li class="separata"><a href="<?= $this->_baseUrl ?>" id="id_inicio"><img src="<?=URL_IMG_ADMIN?>home.png" title="<?= _("home") ?>" /></a></li>
	<li><a href="<?= $this->_baseUrl ?>anyo" id='id_cambio_edicion' title="<?= $edicion->nombre?> - <?= $this->_anyo?>"><img src="<?=URL_SKINS.$this->_anyo . "/" . IMG . "/". $edicion->cartel?>" /></a></li>
	<li  class="separata" ><a href="<?= $this->_baseUrl ?>viewusuario/<?=$usuario->getId()?>" ><img src="<?=BASE_URL_ADMIN . '/vista/skins/commons/img/usuarios/'. $usuario->getLogo()?>" title="<?= $usuario->getNombre()." - ".$usuario->getDescripcion() ?>" /></a></li>
	<li  class="separata" ><a href="<?= $this->_baseUrl ?>logout" ><img src="<?=URL_IMG_ADMIN?>exit_off.png" title="<?= _("logout") ?>" /></a></li>
	</ul>
</div>
<? }?>