<title><?= $this->_title ?></title>
<meta name="description" content="<?=$this->_description?>" />
<meta name="robots" content="noindex,nofollow" />
<meta charset="utf-8" />
<link href="<?=$urlSkin?>css/core.css" rel="stylesheet"/>
<link href="<?=$urlSkin?>css/site.css" rel="stylesheet" />
<? include($pathCommons."includes/literales.phtml");?>	
<script type="text/javascript" language="javascript">
	var urlApp = '<?= $this->_baseUrl ?>';
	var urlImgAdmin = '<?= URL_IMG_ADMIN ?>';
	var modulo = '<?= $this->_controller ?>';
	var ciudad = '<?= UBICACION ?>';
	var osm = <?= json_encode(OSM) ?>;
	var fechaInicio = '<?= empty($fechaInicio)?"":date("d/m/Y",$fechaInicio) ?>';
	var fechaFin = '<?= empty($fechaFin)?"": date("d/m/Y",$fechaFin) ?>';
</script>
<script src="<?=URL_LIBJS?>jquery.js" type="text/javascript" language="javascript" ></script>
<script src="<?=$urlCommons?>js/actions.js" type="text/javascript" language="javascript"></script>
<script src="<?=$urlCommons?>js/forms.js" type="text/javascript" language="javascript"></script>
<script src="<?=URL_LIBJS?>fancybox/jquery.fancybox.pack.js" type="text/javascript" language="javascript" ></script>
<script src="<?=URL_LIBJS?>fancybox/helpers/jquery.fancybox-media.js" type="text/javascript" language="javascript" ></script>
<link rel="stylesheet" href="<?=URL_LIBJS?>fancybox/jquery.fancybox.css" type="text/css" />
<link media="all" type="text/css" href="<?=URL_LIBJS?>jquery-ui/css/jquery-ui.css" rel="stylesheet" />
<script type="text/javascript" src="<?=URL_LIBJS?>jquery-ui/jquery-ui.min.js" ></script>
<script type="text/javascript" src="<?=URL_LIBJS?>comun.js" ></script>