<script type="text/javascript">
<!--
	var gcMsg_ok= '<?= _("feedback.bbdd.ok")?>';
	var gcMsg_ko= '<?= _("feedback.bbdd.ko")?>';
	var gcMsg_loading = '<?= _("feedback.loading")?>';
	var gcMsg_confirmdelete= '<?= _("form.confirm.delete")?>';
	var gcMsg_confirmdeleteimg= '<?= _("form.confirm.delete.img")?>';
	var gcMsg_urlFormat = '<?= _("form.confirm.format.url")?>';
	var gcMsg_email = '<?= _("form.confirm.format.email")?>';
	var gcMsg_revisa = '<?= _("form.error")?>';
	var gcMsg_required = '<?= _("form.campo.obligatorio")?>';
	var gcMsg_selected = '<?= _("form.selected")?>';
	var gcMsg_ubicacion = '<?= _("form.ubicacion")?>';
	var gcMsg_geoerror = '<?= _("geo.error")?>';
	var gcMsg_docname = '<?= _("form.error.docname")?>';
	var gcMsg_date = '<?= _("form.error.date")?>';	
//-->
</script>