<html lang="<?= $this->_lang?>" >
	<head>
		<? include($pathCommons."includes/head.phtml");?>
		<link href="<?=$urlSkin?>css/site.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<article>
		    <header></header>
			<?	include_once($pathCommons."includes" .DS . "menu.phtml"); ?>
			<?	include_once($pathCommons."includes/lang.phtml"); ?>		
			
			<section>
		        <div id="title"><h1><?=$this->_title?></h1></div>
		        <div id="main">
					<?	include_once($pathVista.'controllers'. DS . $this->_controller .".phtml"); ?>
	            </div>
	       </section>
	       <footer>
	       		<? include_once($pathSkin."includes/pie.phtml"); ?>
	       </footer> 
	    </article>
	</body>
</html>