<div id="pie">	
	<p><?=_("Ediciones anteriores :")?> 
		<a href="http://www.lavapiesdecine.net/2012" target="_blank">2012</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2011" target="_blank">2011</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2010" target="_blank">2010</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2009" target="_blank">2009</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2008" target="_blank">2008</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2007" target="_blank">2007</a>&nbsp;&nbsp;   
	   <a href="http://www.lavapiesdecine.net/2006" target="_blank">2006</a>&nbsp;&nbsp;
	   <a href="http://www.lavapiesdecine.net/2005" target="_blank">2005</a>&nbsp;&nbsp;
	   <a href="http://www.lavapiesdecine.net/2004" target="_blank">2004</a>&nbsp;&nbsp;
	</p>
	<p class="logo-pie">
			<a href="http://facebook.com/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/facebook.png" /><span>facebook.com/lavapiesdecine</span></a>
			<a href="http://twitter.com/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/twitter.png" /><span>twitter.com/lavapiesdecine</span></a>
			<a href="http://pinterest.com/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/pinterest.png" /><span>pinterest.com/lavapiesdecine</span></a>
			<a href="http://blip.tv/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/blip.png" /><span>blip.tv/lavapiesdecine</span></a>
	</p>
	<p class="logo-pie">
			<a href='mailto:muestra@lavapiesdecine.net'><img src="<?=$urlSkin?>img/mail.png" /><span>muestra@lavapiesdecine.net</span></a>				   
			<a href="http://xsto.info" target="_blank"><img src="<?=$urlSkin?>img/xstoinfo.png" /><span>hosting: xsto.info</span></a>
			<a href="https://github.com/arturisimo/filmfestCMS" target="_blank"><img src="<?=$urlSkin?>img/github.png" /><span>desarrollado con filmfestCMS</span></a>
	</p>
	<p class="logo-pie">
			<a href="http://creativecommons.org/licenses/by-sa/3.0/deed.es" target="_blank"><img src="http://lavapiesdecine.net/img/logo/licencias/08.png" /><span>Los contenidos generados por la Muestra estan liberados con la licencia Creative commons BY-SA.</span></a>
	</p>
</div>
<strong>unbarrio</strong>muchosmundos<strong>unmundo</strong>muchosbarrios
<div class="footer-main-content"></div>