<?	if(function_exists('apc_cache_info')){ ?>
	<? if($clear){ 
		apc_clear_cache();
	?>
		<h3><?= _("cache.cleaned")?></h3>
	<? } else { ?>
		<p><a href="<?= URL_ADMIN ?>/cache/clear"><?= _("cache.clean")?></a>
	<? }?>
	
	<h3>apc_cache_info</h3>
	<?	\core\util\Log::add(apc_cache_info()); ?> 
	
	<h3>apc_sma_info</h3>
	<?	\core\util\Log::add(apc_sma_info()); ?>
<? } else { ?>
	<h3><?=_("cache.notenabled")?></h3>	
<? } ?>	 
	