<? if(!empty($this->_id)){?>
	
	<!-- TinyMCE -->
	<script src="<?=URL_LIBJS?>tiny_mce/jquery.tinymce.js"></script>
	<script type="text/javascript">
	$().ready(function() {
		$('textarea.tinymce').tinymce({
			script_url : '<?=URL_LIBJS?>tiny_mce/tiny_mce.js',
			theme : "advanced",
			theme_advanced_buttons1 : "bold,italic,underline,separator,link,unlink,separator,image,media,separator,code,fullscreen",
			plugins : "fullscreen",
			entity_encoding : "raw",
			theme_advanced_toolbar_location : "top"
		});
	});
	</script>
	<!-- /TinyMCE -->
	 
	<!-- cartel -->
	<? if(empty($pelicula->cartel)){?>
		<iframe height='100px' width='100px' id='frame_imagen' name='frame_imagen' class='frame oculto' src="<?=URL_ADMIN?>/pelicula/upload"></iframe>
	<? }?>
	<div id="div-img" class="<?= $classUpload ?>">
		<?if(!empty($pelicula->cartel)){?>
			<a href="#" id="delete-img">
				<img width="100px" height="100px" src="<?= $img ?>" id="imagen_uploaded" />
				<span id="change-img" class="<?= $urlPagina."-".$this->_id ?>"></span>
			</a>
		<?} else { ?>
			<form enctype="multipart/form-data" method='post' id="form_imagen" name="form_imagen" action="<?=URL_ADMIN?>/pelicula/upload" target="frame_imagen">
				<p><?=_("form.upload.img")?><br><?= _("form.upload.type")?></p>
				<input name='id_nombre' id='id_nombre' value='<?=$titulo?>' type='hidden'/>
				<input name='galeria' id='galeria' value='<?=$this->_anyo?>' type='hidden'/>
				<input name='id_pelicula' id='id_pelicula' value='<?=$this->_id?>' type='hidden'/>
				<input type="file" name="imagen" id="imagen"  /><br>
			</form>
		<? } ?>	
	</div>
	<!-- cartel -->
	
	<div id="div-img-info">
		<form id='formPelicula' name='formPelicula' method='post'>
			<input name='id' id='id' value='<?=$this->_id?>' type='hidden'/>
			<input name='id_muestra' id='id_muestra' value='<?=$this->_anyo?>' type='hidden'/>
			<input value='<?=$pelicula->id_imagen?>' name='file_imagen' id='file_imagen' type='hidden' />
			<input value='0' name='id_donante' id='id_donante' type='hidden' />
			
			<div class="info-contact">
				<p><strong><?=_("convocatoria.inscripcion")?>:</strong> <?= $pelicula->fecha_alta ?></p>
				<p><strong><?=_("convocatoria.contacto")?>:</strong><br> <?= htmlentities($pelicula->nombre_contacto) ?> / <?= $pelicula->email ?> / <?= $pelicula->telefono ?></p>
			</div>
			
			<!--  info adicional -->
			<div class="info-adicional">
				<label><?=_("convocatoria.datosadicionales")?></label>
				<p><strong><?=_("convocatoria.licencia")?>:</strong> <?= $pelicula->nombre_licencia ?> - <strong><?=_("film.cost")?>:</strong> <?= $pelicula->coste ?></p>
				<p><strong><?=_("convocatoria.recurso")?>:</strong> <?= $pelicula->recursos ?></p>
				<p><strong><?=_("convocatoria.comentarios")?>:</strong> <?= $pelicula->comentarios ?></p>
			</div>
			
			<p><label><?=_("form.pelicula.titulo")?></label>
				<input  value='<?=$pelicula->titulo?>' name='titulo' id='titulo' />
			</p>
				
			<p><label><?=_("convocatoria.proyeccion")?> <span class="small"><?=_("convocatoria.selected")?></span></label>
			<select id='id_proyeccion' name='id_proyeccion'>
				<?= \core\util\UtilPagina::getOptions($proyecciones, $pelicula->id_proyeccion) ?>
			</select></p>
			
			<p class="break"><label><?=_("convocatoria.urlvideo")?> <span class="small">(youtube, blip.tv, dailymotion ...)</span></label>
			<input value='<?=$pelicula->enlace?>' name='id_enlace' id='id_enlace' /></p>
			
			<p><label><?=_("convocatoria.urldescarga")?></label>
			<input value='<?=$pelicula->video_descarga?>' name='id_descarga' id='id_descarga' /></p>
			
			<p><label><?=_("convocatoria.licencia")?> <span class="small"></span></label>
			<select id='id_licencia' name='id_licencia'>
				<?= \core\util\UtilPagina::getOptions($licencias, $pelicula->id_licencia, false) ?>
			</select></p>
			
			<p><label><?=_("form.pelicula.presentacion")?> <span class="small"><?=_("form.pelicula.presentacion.1")?></span></label> 
			<textarea id="id_propio" name="id_propio" rows='2'><?= $pelicula->material_propio ?></textarea>
			</p>
			 
			<p ><label><?=_("convocatoria.ficha")?></label>
			<textarea rows='5' cols='50'  name='id_ficha' id='id_ficha' class="tinymce"><?=$pelicula->ficha_tecnica?></textarea></p>
			
			<p><label><?=_("form.pelicula.sinopsis")?></label> 
			<textarea rows='5' cols='50'  name='id_sinopsis' id='id_sinopsis' class="tinymce" ><?=$pelicula->sinopsis?></textarea></p>
			
			<a href="#" id='b_pelicula' class="boton"><?=_("form.aceptar")?></a>
			
		</form>
	</div>

	
<? } ?>