<? if(empty($img)){?>
	<iframe height='100px' width='100px'  id='frame_imagen' name='frame_imagen' class='frame oculto' src="<?=URL_ADMIN?>/edicion/upload" ></iframe>
<? }?>
<div id="div-img" class="<?= $classUpload ?>">
	<?if(!empty($img)){?>
		<a href="#" id="delete-img">
			<img width="100px" height="100px" src="<?= $img?>" id="imagen_uploaded"/>
			<span id="change-img" class="<?= $urlPagina."-".$this->_id ?>"></span>
		</a>	
	<?} else { ?>
		<p><?= _("form.upload.img")?><br><?= _("form.upload.type")?></p>
		<form enctype="multipart/form-data" method='post' id="form_imagen" name="form_imagen" action="<?=URL_ADMIN?>/edicion/upload" target="frame_imagen">
				<input name='id_nombre' id='id_nombre' value='<?=$nombre?>' type='hidden'/>
				<input type="file" name="imagen" id="imagen"  /><br>
		</form>
	<? } ?>	
</div>

<div id="div-img-info">
	<form id='form_convocatorias' name='form_convocatorias' method='post'>
		<input value='<?=$fileImg?>' name='file_imagen' id='file_imagen' type='hidden' />
		<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
			
		<label><?=$nombre?></label>		
		
		<label><?=_("form.link")?> </label>
		<select name='id_url' id='id_url'> 
			<?= \core\util\UtilPagina::getOptions($paginas, $url) ?>
		</select> 
		
		<label><?= _("form.description")?></label> 
		<textarea rows="4" name='descripcion' id='descripcion'><?=$descripcion?></textarea>
		
		<a href="#" id='b_convocatorias' class="boton"><?=_("form.aceptar")?></a>	

	</form>
</div>