<form id='form_lang' name='form_lang' method='post' >
	<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
	
	<label><?=_("form.nombre")?></label>
	<input name='id_nombre' id='id_nombre' value="<?= $nombre ?>" />
	
	<label><?= _("form.lang.id")?></label>
	<input name='id_codigo' id='id_codigo' value="<?= $codigo ?>" />
	
	<label><?= _("form.lang.codificacion")?></label>
	<input name='id_codificacion' id='id_codificacion' value="<?= $codificacion ?>" />
	
	<a href="#" id='b_lang' class="boton"><?=_("form.aceptar")?></a>
	
</form>