<!-- TinyMCE -->
<script src="<?=URL_LIBJS?>tiny_mce/jquery.tinymce.js"></script>
<script type="text/javascript">
$().ready(function() {
	$('textarea.tinymce').tinymce({
		script_url : '<?=URL_LIBJS?>tiny_mce/tiny_mce.js',
		theme : "advanced",
		theme_advanced_buttons1 : "bold,italic,underline,separator,link,unlink,separator,image,media,separator,code,fullscreen",
		plugins : "fullscreen",
		theme_advanced_toolbar_location : "top"
	});
});
</script>
<!-- /TinyMCE -->

<!-- cartel -->
<? if(empty($img)){?>
	<iframe height='100px' width='100px' id='frame_imagen' name='frame_imagen' class='frame oculto' src="<?=URL_ADMIN?>/pelicula/upload" ></iframe>
<? }?>
<div id="div-img" class="<?= $classUpload ?>">
	<?if(!empty($img)){?>
		<a href="#" id="delete-img">
			<img width="100px" height="100px" src="<?= $img?>" id="imagen_uploaded" />
			<span id="change-img" class="<?= $urlPagina."-".$this->_id ?>"></span>
		</a>
	<?} else { ?>
		<form enctype="multipart/form-data" method='post' id="form_imagen" name="form_imagen" action="<?=URL_ADMIN?>/pelicula/upload" target="frame_imagen">
			<p><?=_("form.upload.img")?><br><?= _("form.upload.type")?></p>
			<input name='id_nombre' id='id_nombre' value='<?=$titulo?>' type='hidden'/>
			<input name='galeria' id='galeria' value='<?=$this->_anyo?>' type='hidden'/>
			<input name='id_pelicula' id='id_pelicula' value='<?=$this->_id?>' type='hidden'/>
			<input type="file" name="imagen" id="imagen"  /><br>
		</form>
	<? } ?>	
</div>
<!-- cartel -->

<div id="div-img-info">
	<form id='formPelicula' name='formPelicula' method='post'>
		<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
		<input name='id_muestra' id='id_muestra' value='<?=$this->_anyo?>' type='hidden'/>
		<input value='<?=$idImgPelicula?>' name='file_imagen' id='file_imagen' type='hidden' />
		<input type="hidden" value='' name='id_descarga' id='id_descarga' />
		
		<label><?=_("form.pelicula.titulo")?></label><input  value='<?=$titulo?>' name='titulo' id='titulo' required />
		<label><?=_("form.pelicula.proyeccion")?> <span class="small"><?=_("form.pelicula.proyeccion.1")?>: <a href="<?=URL_ADMIN?>/proyeccion"><?=_("form.pelicula.proyeccion.2")?></a></span></label>
		<select id='id_proyeccion' name='id_proyeccion'>
			<?= \core\util\UtilPagina::getOptions($proyecciones, $idProyeccion) ?>
		</select>
		<label><?=_("form.pelicula.agradecimientos")?> <span class="small"><?=_("form.pelicula.agradecimientos.1")?>: <a href="<?=URL_ADMIN?>/agradecimiento"><?=_("form.pelicula.agradecimientos.2")?></a></span></label>
			<select id='id_donante' name='id_donante'>
			<?= \core\util\UtilPagina::getOptions($agradecimientos, $idAgradecimiento) ?>
			</select>
		
		
		<label><?=_("form.pelicula.trailer")?> <span class="small"><?=_("form.pelicula.trailer.ejemplo")?></span></label>
		<input value='<?=$url?>' name='id_enlace' id='id_enlace' placeholder="http://" />
		
		<label><?=_("form.pelicula.licencia")?> <span class="small"></span></label>
		<select id='id_licencia' name='id_licencia'>
			<?= \core\util\UtilPagina::getOptions($licencias, $idLicencia, false) ?>
		</select>
		
		<label><?=_("form.pelicula.presentacion")?> <span class="small"><?=_("form.pelicula.presentacion.1")?></span></label> 
		<textarea id="id_propio" name="id_propio"  rows='2'><?= $txtPresentacion ?></textarea>
		
				
		<label><?=_("form.pelicula.ficha")?> </label>
		<textarea id="id_ficha" name="id_ficha" class="tinymce"><?= $fichaTecnica ?></textarea>
		
		<label><?=_("form.pelicula.sinopsis")?> </label>
		<textarea id="id_sinopsis" name="id_sinopsis" class="tinymce"><?= $sinopsis ?></textarea>
		
		<p><a href="#" id='b_pelicula' class="boton"><?=_("form.aceptar")?></a></p>	
		
	</form>
</div>