<? if(empty($img)){?>
	<iframe height='100px' width='100px'  id='frame_imagen' name='frame_imagen' class='frame oculto' src="<?=URL_ADMIN?>/perfil/upload"></iframe>
<? }?>
<div id="div-img" class="<?= $classUpload ?>">
	<?if(!empty($img)){?>
		<a href="#" id="delete-img">
			<img width="100px" height="100px" src="<?= $img?>" id="imagen_uploaded" />
			<span id="change-img" class="<?= $urlPagina."-".$this->_id ?>"></span>
		</a>	
	<?} else { ?>
		<p><?=_("form.upload.img")?><br><?= _("form.upload.type")?></p>	
		<form enctype="multipart/form-data" method='post' id="form_imagen" name="form_imagen" action="<?=URL_ADMIN?>/perfil/upload" target="frame_imagen">
				<input name='id_nombre' id='id_nombre' value='<?=$nombre?>' type='hidden'/>
				<input name="id_perfil" id="id_perfil" type="hidden" value="<?=$this->_id?>" >
				<input type="file" name="imagen" id="imagen"  />
		</form>
	<? } ?>	
</div>

<div id="div-img-info">
	<form id='form_perfil' name='form_perfil' method='post'>
		<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
		<input value='<?=$fileImg?>' name='file_imagen' id='file_imagen' type='hidden' />
		<input type="hidden" id="modulosSelected" value="" name="modulosSelected" />
		
		<label><?=_("form.perfil")?></label>
		<input value='<?= $nombre ?>' name='nombre' id='nombre' />
		
		<p class="select"><label><?=_("form.modulos")?></label>
		<select name='modulosDisponibles' id='modulosDisponibles' class="availables"  size=5>
			<?= \core\util\UtilPagina::getOptions($modulosPosibles, 0, false) ?>
		</select>
		</p>
		<p class="arrow">
			<img src="<?=URL_IMG_ADMIN?>right_off.png" id="right" />
			<img src="<?=URL_IMG_ADMIN?>left_off.png" id="left" />
		</p>
		<p class="select"><label><?=_("form.modulos.selected")?></label>
			<select name='modulos' id='modulos' multiple="multiple" class="selecteds" size=5>
				<?= \core\util\UtilPagina::getOptions($modulos, 0, false) ?>
			</select>
		</p>
		
		<? if (!empty($nombre)){ ?>
			<label><?=_("form.descripcion.breve")?></label>
			<?= _("profile.$nombre.description")?>
		<? } ?>
		
		<p><a href="#" id='b_perfil' class="boton"><?=_("form.aceptar")?></a></p>
	</form>
</div>