<!-- TinyMCE -->
<script src="<?=URL_LIBJS?>tiny_mce/jquery.tinymce.js"></script>
<script type="text/javascript">
$().ready(function() {
	$('textarea.tinymce').tinymce({
		script_url : '<?=URL_LIBJS?>tiny_mce/tiny_mce.js',
		theme : "advanced",
		theme_advanced_buttons1 : "bold,italic,underline,separator,link,unlink,separator,image,media,separator,code,fullscreen",
		plugins : "fullscreen",
		relative_urls : true,
		entity_encoding : "raw",
		theme_advanced_toolbar_location : "top"
	});
});
</script>
<!-- /TinyMCE -->
<form id='form_texto' name='form_texto' method='post'>
	<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
	<input name='id_muestra' id='id_muestra' value='<?= $this->_anyo ?>' type='hidden'/>
	
	<label> <?=_("form.titulo")?></label>
	<input value='<?=$titulo?>' name='id_titulo' id='id_titulo' required />
	
	<label><?=_("form.txt")?></label>
	<textarea id="texto" name="texto" class="tinymce" rows="20" ><?= $texto?></textarea>
	
	<label><?=_("form.lang")?> </label>
		<select name='lang' id='lang'>
		<?= \core\util\UtilPagina::getOptions($langs, $lang) ?>
		</select>
	
	<label><?= _("form.txt.galeria")?></label> 
	<select name="id_galeria" id="id_galeria">
		<?= \core\util\UtilPagina::getOptions($galerias, $idGaleria) ?>
	</select> 
	
	<a href="#" id='b_texto' class="boton"><?=_("form.aceptar")?></a>
	
</form>