<meta charset="utf-8" />
<meta http-equiv="Cache-control" content="public">
<title><?= $this->_title ?> &mdash; <?= $edicion->nombre ?></title>
<meta content="<?=$this->_description?>" name="Description" />
<meta content="lavapiesdecine" name="Author" />
<meta content="lavapiesdecine" name="Origen" />
<meta content="Lavapiesdecine" name="Generator" />
<link rel="icon" href="<?=URL_IMG?>logo_lavapies_firma.JPG"/>
<script src="<?=URL_LIBJS?>jquery.js" type="text/javascript" ></script>
<script src="<?=URL_LIBJS?>comun.js" type="text/javascript" ></script>
<script src="<?=URL_LIBJS?>fancybox/jquery.fancybox.pack.js" type="text/javascript"></script>
<script src="<?=URL_LIBJS?>fancybox/helpers/jquery.fancybox-media.js" type="text/javascript"></script>
<script src="<?=$urlCommons?>js/common.js" type="text/javascript"></script>
<link rel="stylesheet" href="<?=URL_LIBJS?>fancybox/jquery.fancybox.css" type="text/css" >
<script type="text/javascript">
	var urlApp = '<?= BASE_URL ?>/';
	var modulo = '<?= $this->_controller ?>';
	var osm = <?= json_encode(OSM && !$this->_data->getRequest()->getMovil()) ?>;
</script>
<?	include_once($pathCommons. "google-analytics.html"); ?>
<script type="text/javascript">
<!--
	var gcMsg_email= "<?= _("form.confirm.format.email")?>";
	var gcMsg_revisa= "<?= _("form.error")?>";
	var gcMsg_required= "<?= _("form.campo.obligatorio")?>";
//-->
</script>

<? $txtMenu = array( _("contacta.menu"), _("home.menu"), _("programa.menu"), _("espacios.menu"), _("muestras.menu"), _("escaparate.menu"), _("faq.menu"), _("licencias-libres.menu"), _("convocatoria-abierta.menu"), _("inscripcion.menu"), _("bases-convocatoria.menu"), _("seleccion.menu"), _("obras-recibidas.menu"), _("modelos-de-negocio.menu"), _("convocatoria.menu") );?>
<? $txtMenuDescription = array( _("contacta.description"), _("home.description"), _("programa.description"), _("espacios.description"), _("muestras.description"), _("escaparate.description"), _("faq.description"), _("licencias-libres.description"), _("convocatoria-abierta.description"), _("inscripcion.description"), _("bases-convocatoria.description"), _("seleccion.description"), _("obras-recibidas.description"), _("modelos-de-negocio.description"), _("convocatoria.description") );?>
