<? $txtMenu = array( _("contacta.menu"), _("home.menu"), _("programa.menu"), _("espacios.menu"), _("muestras.menu"), _("escaparate.menu"), _("faq.menu"), _("licencias-libres.menu"), _("convocatoria-abierta.menu"), _("inscripcion.menu"), _("bases-convocatoria.menu"), _("seleccion.menu"), _("obras-recibidas.menu") );?>
<? $txtMenuDescription = array( _("contacta.description"), _("home.description"), _("programa.description"), _("espacios.description"), _("muestras.description"), _("escaparate.description"), _("faq.description"), _("licencias-libres.description"), _("convocatoria-abierta.description"), _("inscripcion.description"), _("bases-convocatoria.description"), _("seleccion.description"), _("obras-recibidas.description") );?>

<nav id="menu">
	<?= \core\util\UtilPagina::menu($menu, $urlPagina, $this->_baseUrl, $idControllerMenu) ?>
</nav>

<? if(isset($subMenu) && count($subMenu)>0){?>
	<nav id="submenu">
		<?=	\core\util\UtilPagina::menu($subMenu, $urlPagina, $this->_baseUrl, $idControllerMenu) ?>
	</nav>	
<?}?>