<div id="msg" class="oculto"></div>
<form id='form-contacta' method='post' >
	<input name='email' id="email" type='text' type="email" required placeholder="<?=_("inscripcion.email")?>">
	<input name='asunto' id="asunto" type='text' required placeholder="<?= _("contacta.asunto") ?>">
	<textarea rows=10 name='comentario' id="comentario" required placeholder="<?= _("contacta.mensaje") ?>"></textarea>
	<p><a href="#" id='b-mail' class="boton"><?=_("contacta.enviar")?></a></p>
</form>