<div id='escaparate'>
	<? foreach ($imagenes as $imagen) {
		$tag = "";
		$url = URL_IMG."galerias/".$imagen->galeria."/".$imagen->imagen;
		$video = false;
		if (!empty($imagen->url_video)){
			$url = $imagen->url_video;
			$tag = "width='550px' height='400px'";
			$video = true;
			$img = \core\util\Util::getImageVideo($url);
		} else {
			$img = URL_IMG . "galerias/" . $imagen->galeria . "/" . THUMBNAIL . "/". $imagen->imagen;
		}
	?>
		<div>
		<a href='<?=$url?>' class="fancybox" rel="<?=$imagen->galeria?>" title='<?=$imagen->descripcion?>' >
			<img width='100px' height='100px' src='<?=$img?>' alt='<?=$imagen->descripcion?>'>
			<?php  if($video) {?><span></span><?php } ?>
		</a>
		</div>
	<? }?> 
</div>