<div id='escaparate'>
	<? foreach ($imagenes as $imagen) {
		$tag = "";
		$url = URL_IMG."galerias/".$imagen->galeria."/".$imagen->imagen;
		$video = false;
		if (!empty($imagen->url_video)){
			$url = $imagen->url_video;
			$tag = "width='550px' height='400px'";
			$video = true;
		}
	?>
		<div>
		<a href='<?=$url?>' class="fancybox" rel="<?=$imagen->galeria?>" title='<?=$imagen->descripcion?>' >
			<img width='100px' height='100px' src='<?=URL_IMG."galerias/".$imagen->galeria."/".THUMBNAIL . "/".$imagen->imagen;?>' alt='<?=$imagen->descripcion?>'>
			<?php  if($video) {?><span></span><?php } ?>
		</a>
		</div>
	<? }?> 
</div>