	<script src="<?=$urlCommons?>js/inscripcion.js" type="text/javascript" language="javascript"></script>	
	<link href="<?=$urlSkin?>css/inscripcion.css" rel="stylesheet" type="text/css" />
	
	<div id="formularios">
		<div id="div-contacto" class="">
			<form id='form_contacto' name='form_contacto' method='post'>
				<h3><?=_("inscripcion.datos.contacto")?></h3>
				<p><?=_("inscripcion.datos.contacto.1")?></p>
				<label id="label-nombre"><?=_("inscripcion.nombre")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><input type="text" name="id_nombre" id="id_nombre" required />
				<label id="label-email"><?=_("inscripcion.email")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><input type="email" name="id_email" id="id_email" class="minusculas" required type="email" />
				<label id="label-telefono"><?=_("inscripcion.telefono")?></label><input type="tel" name="id_telefono" id="id_telefono" maxlength="15"/>
				<label id="label-tipo-contacto"><?=_("inscripcion.tipocontacto")?></label>
				<select name="id_tipocontacto" id="id_tipocontacto"  multiple="multiple" size="3">
					<option value="01" selected="selected"><?=_("inscripcion.tipocontacto01")?></option>
					<option value="02"><?=_("inscripcion.tipocontacto02")?></option>
					<option value="03"><?=_("inscripcion.tipocontacto03")?></option>
				</select>
				<p class="enlace-formulario"><a href="#" id="b-contacto" class="boton-inscripcion"><?=_("inscripcion.datos.obra")?> &raquo;</a></p>
			</form>
		</div>
		<div id="div-pelicula" class="oculto">
			<form id='form_pelicula' method='post'>
				<h3><?=_("inscripcion.datos.obra")?></h3>
				<p><?=_("inscripcion.datos.obra.1")?></p>
				<label id="label-titulo"><?=_("inscripcion.datos.titulo")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><input id="id_titulo" type="text" name="id_titulo" maxlength="100"  required />									
				<label id="label-autor"><?=_("inscripcion.datos.autor")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><input type="text" name="id_autor" id="id_autor" required />
				<label id="label-duracion"><?=_("inscripcion.datos.duracion")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><input type="text" class="campo-mini" name="id_minutos" id="id_minutos" /> <?=_("inscripcion.datos.minutos")?>   <input type="text" class="campo-mini" name="id_segundos" id="id_segundos" /> <?=_("inscripcion.datos.segundos")?>
				<label id="label-anyo"><?=_("inscripcion.datos.anyo")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><input type="text" name="id_anyo" id="id_anyo" class="campo-mini" maxlength="4" required />
				<label id="label-genero"><?=_("inscripcion.datos.genero")?> </label><input type="text" name="id_genero" id="id_genero" />
				<label id="label-pais"><?=_("inscripcion.datos.pais")?></label><input type="text" name="id_pais" id="id_pais" />
				<label id="label-sinopsis"><?=_("inscripcion.datos.sinopsis")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><textarea name="id_sinopsis" id="id_sinopsis" required ></textarea>
				<label id="label-tecnica"><?=_("inscripcion.datos.tecnica")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><textarea name="id_tecnica" id="id_tecnica"></textarea>
				<label id="label-web"><?=_("inscripcion.datos.web")?> </label><input type="text" name="id_web" id="id_web" placeholder="http://" class="minusculas" />
				<p class="enlace-formulario"><a href="#" id="b-pelicula" class="boton-inscripcion"><?=_("inscripcion.datos.adicional")?> &raquo;</a></p>
			</form>
		</div>	
		<div id="div-adicional"  class="oculto">
			<form id='form_adicional' method='post'>
				<h3><?=_("inscripcion.datos.adicional")?></h3>
				<p><?=_("inscripcion.datos.adicional.1")?></p>
				<label id="label-coste"><?=_("inscripcion.datos.coste")?></label><input type="text" name="id_coste" id="id_coste" />
				<label id="label-recursos"><?=_("inscripcion.datos.recursos")?></label><textarea name="id_recursos" id="id_recursos"></textarea>
				<label id="label-comentario"><?=_("inscripcion.datos.comentarios")?></label><textarea name="id_comentarios" id="id_comentarios"></textarea>
				<p class="enlace-formulario"><a href="#" id="b-adicional" class="boton-inscripcion"><?=_("incripcion.licencia")?> &raquo;</a></p>
			</form>
		</div>	
		<div id="div-licencia"  class="oculto">
			<form id='form_licencia' method='post'>
				<h3><?=_("incripcion.licencia")?></h3>
				<p><?=_("incripcion.licencia.1")?></p>
				
				
					<p>Creative Commons 3.0</p>
				
						<input class="radio" type="radio" name="id_licencia" id="lic_04" value="04"/> <img id="img_04"  src="<?=URL_LOGO?>licencias/04.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_05" value="05"/> <img id="img_05"  src="<?=URL_LOGO?>licencias/05.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_06" value="06"/> <img id="img_06"  src="<?=URL_LOGO?>licencias/06.png" /><br>
				
						<input class="radio" type="radio" name="id_licencia" id="lic_07" value="07"/> <img id="img_07"  src="<?=URL_LOGO?>licencias/07.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_08" value="08"/> <img id="img_08"  src="<?=URL_LOGO?>licencias/08.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_09" value="09"/> <img id="img_09"  src="<?=URL_LOGO?>licencias/09.png" /><br>
				
					<p>ColorIURIS</p>
				
						<input class="radio" type="radio" name="id_licencia" id="lic_10" value="10"/> <img id="img_10"  src="<?=URL_LOGO?>licencias/10.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_11" value="11"/> <img id="img_11"  src="<?=URL_LOGO?>licencias/11.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_12" value="12"/> <img id="img_12"  src="<?=URL_LOGO?>licencias/12.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_13" value="13"/> <img id="img_13"  src="<?=URL_LOGO?>licencias/13.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_14" value="14"/> <img id="img_14"  src="<?=URL_LOGO?>licencias/14.png" /><br>
				
						<input class="radio" type="radio" name="id_licencia" id="lic_15" value="15"/> <img id="img_15"  src="<?=URL_LOGO?>licencias/15.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_16" value="16"/> <img id="img_16"  src="<?=URL_LOGO?>licencias/16.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_17" value="17"/> <img id="img_17"  src="<?=URL_LOGO?>licencias/17.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_18" value="18"/> <img id="img_18"  src="<?=URL_LOGO?>licencias/18.png" /><br>
						<input class="radio" type="radio" name="id_licencia" id="lic_19" value="19"/> <img id="img_19"  src="<?=URL_LOGO?>licencias/19.png" /><br>
				
					<p>Aire Incondicional 1.01</p>
					<input class="radio" type="radio" name="id_licencia" id="lic_20" value="20"/> <img id="img_20"  src="<?=URL_LOGO?>licencias/20.png" />
				
					<p>Art Libre 1.3</p>
					<input class="radio" type="radio" name="id_licencia" id="lic_21" value="21"/> <img id="img_21" src="<?=URL_LOGO?>licencias/21.png" /> 
				
					<p>Against DRM 2.0</p>
					<input class="radio" type="radio" name="id_licencia" id="lic_22" value="22"/> <img id="img_22" src="<?=URL_LOGO?>licencias/22.png" />
				
					<p><?=_("incripcion.licencia.dominiopublico")?></p>
					<input class="radio" type="radio" name="id_licencia" id="lic_03" value="03"/> <img id="img_03"  src="<?=URL_LOGO?>licencias/03.png" />
				
				<p class="enlace-formulario"><a href="#" id="b-licencia" class="boton-inscripcion"><?=_("inscripcion.datos.multimedia")?> &raquo;</a></p>
			</form>
		</div>	
				
		<div id="div-multimedia" class="oculto">
			<h3><?=_("inscripcion.datos.multimedia")?></h3>
			<p><?=_("inscripcion.datos.multimedia.1")?></p>
			<form enctype="multipart/form-data" method='post' id="form_imagen" name="form_imagen" action="<?=BASE_URL?>/inscripcion/upload" target="frame_imagen">
				<label id="label-imagen" ><?=_("inscripcion.datos.multimedia.upload")?></label><input type="file" name="imagen" id="imagen">
			</form>
			<span class="texto-mini"><?=_("inscripcion.datos.multimedia.img")?><?= ini_get('upload_max_filesize')?></span>
			<iframe height='100px' width='100%'  id='frame_imagen' name='frame_imagen' class='frame oculto' scrolling='no' frameborder="0"  src='<?=BASE_URL?>/inscripcion/upload' ></iframe>
			<div id="div-cargando" class="oculto"><img src="<?=BASE_URL_WEB?>/vista/skins/commons/img/loading.gif" /></div>
			<form id='form_multimedia' method='post'>
				<label id="label-video" ><?=_("inscripcion.datos.multimedia.urlstreaming")?> <span>(<?=_("inscripcion.obligatorio")?>)</span></label><input type="text" name="id_video" id="id_video" placeholder="http://" class="minusculas" required />
				<label id="label-videodescarga" ><?=_("inscripcion.datos.multimedia.urldownload")?></label><input type="text" name="id_videodescarga" id="id_videodescarga" placeholder="http://" class="minusculas" />
				<p class="enlace-formulario"><a href="#" id="b-multimedia" class="boton-inscripcion">koniek &raquo;</a></p>
			</form>
		</div>
		
		<div id="div-confirmacion" class="oculto"></div>
		
	</div>
	
	<div id="resumen">
		<div id="msg" class="msg oculto"></div>
		<div id="msg-confirmacion" class="msg-confirmacion oculto"></div>
		<div id="resumen-contacto" class="oculto"></div>
		<div id="resumen-pelicula" class="oculto"> </div>
		<div id="resumen-adicional" class="oculto"></div>
		<div id="resumen-licencia" class="oculto"></div>
	</div>