<p> <?=_("recepcion.presentacion.1")?> <strong><?= $total?></strong> <?=_("recepcion.presentacion.2")?></p>

<table class='listado'>
	<tr class='cabecera'>
		<th></th><th><?= _("recepcion.titulo")?></th><th><?=_("recepcion.ficha")?></th><th></th><th></th>
	</tr>
	
	<? foreach ($peliculas as $pelicula) { ?>
		<tr>
			<td><a title='<?=$pelicula->titulo?>' href='<?=BASE_URL?>/pelicula/<?=$pelicula->id?>/<?=\core\util\Util::stripAccents($pelicula->titulo)?>'>
				<img height='50px' width='50px' src='<?= $pelicula->cartel ?>' title='<?=$pelicula->titulo?>' alt='<?=$pelicula->titulo?>' />
				</a>
			</td>
			<td style='width:150px;'><a style='margin:0px 2px;' title='<?=$pelicula->titulo?>' href='<?=BASE_URL?>/pelicula/<?=$pelicula->id?>/<?=\core\util\Util::stripAccents($pelicula->titulo)?>'><strong><?=$pelicula->titulo?></strong></a></td>
			<td style='width:450px;'><?=$pelicula->autor?> <br> <?=$pelicula->duracion?> / <?=$pelicula->anyo?> <?=!empty($pelicula->genero) ? " / ".$pelicula->genero:"" ?> <?=!empty($pelicula->pais) ? " / ".$pelicula->pais:"" ?>  <?=(!empty($pelicula->nombre_licencia) && $pelicula->nombre_licencia!='Copyright') ? " / ".$pelicula->nombre_licencia:"" ?>
			<br><?=\core\util\Util::substring($pelicula->sinopsis, 67)?></td>
			<td><?	if(!empty($pelicula->video)){ ?>
						<a href='<?=$pelicula->video?>' class='fancybox' title='<?=$pelicula->titulo."  -  ".$pelicula->autor?>'><?=_("recepcion.vervideo")?></a>
				<?	}?>
			</td>
		</tr>
	<? } ?>
</table>

<?	if ($totalPaginas > 1){ ?>
	  	<div id='paginacion'><?= \core\util\UtilPagina::paginacion($pag, $totalPaginas, $this->_baseUrl.$urlPagina)?></div>	
<?	} ?>