<p> <?= _("geo.txt") ?> </p>

<form id='form_geo' name='form_geo' method='post'>
	<input id="id_longitud" name="id_longitud" type="hidden" value="<?=$longitud?>" />
    <input id="id_latitud" name="id_latitud" type="hidden" value="<?=$latitud?>" />

	<label><?=_("form.espacio.direccion")?></label>
	<input value='<?=$direccion?>' name='direccion' id='direccion' required />
	
	<label><?= _("form.ubicacion")?>: <span id='id_ciudad' ><?= $direccion ?></span></label>
	
	<? if(OSM) {?>
		<script type="text/javascript" src="<?=URL_LIBJS?>openlayer/OpenLayers.js"> </script>
	<? } else {?>
		<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
	<? } ?>		
	
	<div id="map"></div>
	
	<p>
		<a href="#" id='b_checkgeo' class="boton"><?=_("form.check.geo")?></a>
		<a href="#" id='b_geo' class="boton"><?=_("form.aceptar")?></a>
		<a href="<?=URL_INSTALL."/".$this->_next[0]?>" id='b_geo_next' class="boton oculto"><?=$this->_next[1]?> &raquo;</a>
	</p>
</form>	