<p>Para la gesti&oacute;n de contenidos de la <a href="http://lavapiesdecine.net">Muestra de cine de Lavapi&eacute;s</a> hemos desarrollado un gestor de contenidos para la publicaci&oacute;n en la web las fichas de las pel&iacute;culas, proyecciones en la semana de la muestra, gestionar la inscripci&oacute;n en la convocatoria abierta...</p>
<p>Como nos gusta la cultura libre y pensamos que este software le puede venir bien a quien monte un festival, hemos decidido liberar el c&oacute;digo bajo <a href="http://www.gnu.org/licenses/agpl-3.0.en.html">licencia GNU</a></p>
<p>Para desarrollar este CMS hemos partido de varias tecnolog&iacute;as:
	<ul>
		<li><a href="http://w3.org" target="_blank">HTML 5</a> / <a href="http://php.net/" target="_blank">php 5.3</a> / <a href="http://www.mysql.com" target="_blank">mySQL </a></li>
		<li><a href="http://http://jquery.com" target="_blank">jQuery</a> / <a href="http://www.tinymce.com/" target="_blank">TinyMCE</a> / <a href="http://fancybox.net/" target="_blank">fancybox</a></li>
		<li><a href="http://commons.wikimedia.org/wiki/Crystal_Clear" target="_blank">Crystal Clear</a></li>
		<li><a href="http://www.fpdf.org" target="_blank">FPDF</a> / <a href="http://www.josscrowcroft.com" target="_blank">php.mo</a></li> 
		<li><a href="http://www.openstreetmap.org" target="_blank">OpenStreeMap</a> <a href="http://openlayers.org" target="_blank">OpenLayers</a> / <a href="https://developers.google.com/maps/" target="_blank">Google Maps</a> </p></li>
	</ul> 
<p>Se puede descargar en&nbsp;<a href="https://github.com/lavapiesdecine/filmfestCMS" target="_blank">https://github.com/lavapiesdecine/filmfestCMS</a>&nbsp;pero todav&iacute;a est&aacute; en fase de pruebas.</p>
<p>Pantallazos:</p>
<div id="galeria-texto">
	<a href="../img/galerias/filmfestcms/20130613110648.jpg" class="fancybox" rel="filmfestcms" title="Panel de administraci&oacute;n">
		<img width="100px" height="100px" src="../img/galerias/filmfestcms/tn/20130613110648.jpg" alt="Panel de administraci&oacute;n">
	</a>
	<a href="../img/galerias/filmfestcms/20130613110608.jpg" class="fancybox" rel="filmfestcms" title="Ficha de pel&iacute;cula visible en la web">
		<img width="100px" height="100px" src="../img/galerias/filmfestcms/tn/20130613110608.jpg" alt="Ficha de pel&iacute;cula visible en la web">
	</a>
	
	<a href="../img/galerias/filmfestcms/20130613110641.jpg" class="fancybox" rel="filmfestcms" title="Administraci&oacute;n de pel&iacute;culas">
		<img width="100px" height="100px" src="../img/galerias/filmfestcms/tn/20130613110641.jpg" alt="Administraci&oacute;n de pel&iacute;culas">
	</a>
	
	<a href="../img/galerias/filmfestcms/20130613160625.jpg" class="fancybox" rel="filmfestcms" title="Programa de proyecciones">
		<img width="100px" height="100px" src="../img/galerias/filmfestcms/tn/20130613160625.jpg" alt="Programa de proyecciones">
	</a>
	
	<a href="../img/galerias/filmfestcms/20130613160654.jpg" class="fancybox" rel="filmfestcms" title="Gestor de proyecciones">
		<img width="100px" height="100px" src="../img/galerias/filmfestcms/tn/20130613160654.jpg" alt="Gestor de proyecciones">
	</a>
	
	<a href="../img/galerias/filmfestcms/20130615120651.jpg" class="fancybox" rel="filmfestcms" title="Gestor de nuevas p&aacute;ginas">
		<img width="100px" height="100px" src="../img/galerias/filmfestcms/tn/20130615120651.jpg" alt="Gestor de nuevas p&aacute;ginas">
	</a>
</div>
<p><?=_("intro.txt")?>
<p><a href="<?=URL_INSTALL."/".$this->_next[0]?>" id='b_intro' class="boton"><?=$this->_next[1]?> &raquo;</a></p>	

