<p>Para la gesti&oacute;n de contenidos de la <a href="http://lavapiesdecine.net">Muestra de cine de Lavapi&eacute;s</a> hemos desarrollado un gestor de contenidos para la publicaci&oacute;n en la web las fichas de las pel&iacute;culas, proyecciones en la semana de la muestra, gestionar la inscripci&oacute;n en la convocatoria abierta...</p>
<p>Como nos gusta la cultura libre y pensamos que este software le puede venir bien a quien monte un festival, hemos decidido liberar el c&oacute;digo bajo <a href="http://www.gnu.org/licenses/agpl-3.0.en.html">licencia GNU</a></p>
<p>Para desarrollar este CMS hemos partido de varias tecnolog&iacute;as:<br> <a href="http://php.net/" target="_blank">php 5.3</a> / <a href="http://www.mysql.com" target="_blank">mySQL </a>/ <a href="http://http://jquery.com" target="_blank">jQuery</a> / <a href="http://www.tinymce.com/" target="_blank">TinyMCE</a> / <a href="http://fancybox.net/" target="_blank">fancybox</a> / <a href="http://commons.wikimedia.org/wiki/Crystal_Clear" target="_blank">Crystal Clear</a> / FPDF / OpenStreeMap </p> 
<p>Se puede descargar en&nbsp;<a href="https://github.com/lavapiesdecine/filmfestCMS" target="_blank">https://github.com/lavapiesdecine/filmfestCMS</a>&nbsp;pero todav&iacute;a est&aacute; en fase de pruebas.</p>
<p>Pantallazos:</p>

<p><?=_("intro.txt")?>
<p><a href="<?=URL_INSTALL."/".$this->_next[0]?>" id='b_intro' class="boton"><?=$this->_next[1]?> &raquo;</a></p>	

